- zq.js
-  Rename `swapClass` to `replaceClass`
-  Make `toggleClass` work like `classList.toggle`
- Use `DOMTokenList` methods internally
> Update zQ methods and arguments

- test/index.html
- test/index.js
- zq.js
Use `dispatchEvent` to trigger `DOMContentLoaded` event if
`document.readState` is no longer "loading".
This way, event handlers run properly because the event is actually triggered and with all event target/properties set.
> Update `ready` method

- zq.js
Resolves #31
Allows for listening for `hashchange` events. Probably only
useful on `window`.
> Add hashchange method

- socialshare.js
Fixes #47
-  Correct typo in `const` for LinkedIn URL
> Fix LinkedIn URL

- socialshare.js
Add email to `SocialShare`, using `mailto:` URIs
> Patch share email

- zq.js
Was binding to rest (`...args`)[1]
Fixes #53
-  Use `callback.bind(node)` instead of `args[0].bind(node)`
> Bind ready callback to callback

- zq.js
- Re-add `event` as   argument to `zq.on`
> Fix missing event when adding event listeners

- README.md
- json_response.js
- test/funcs.js
- test/index.html
- test/index.js
- zq.js
- `zQ.prototype.each` now takes an optional `sync` argument
- If `sync` is false, return a `Promise.resolve()`
- For all DOM opreations making use of the `...rest` operator, default
to async
- All event listeners are added async, returning `this`
- `json_response` now uses async
- Update `README.md`
> Allow DOM operations to be async

- functions.js
Can be used to increment a value every time it is retrieved. Resolves #61 
```js
const options = setIncrementor({
duration: 400,
easing: 'ease-in-out'
}, {
increment: 400,
key: 'delay'
});
[...document.querySelectorAll('.animation-stagger')].forEach(el => {
el.animate([
{transform: 'none'},
{transform: 'rotate(1turn)'}
], options);
});
```
> Add function `setIncrementor`

- asyncPrompts.js
Using `<dialog>`  and `async` functions, this allows for constomization of such dialogs and does not stop script execution unless `await` is used.
Does not overwrite default functions, but can be made to do so:
```js
import {prompt, confirm, alert} from './asyncDialog.js';
window.alert = alert;
window.prompt = prompt;
window.confirm = confirm;
alert('This no longer stops execution and can be styled with CSS');
```
> Add async functions for prompt, confirm, and alert

- asyncDialog.js
- mutations.js
- package.json
- shims.js
- test/funcs.js
- Add support for `<form method=""dialog">`
- Correctly handle `returnValue` on close events
- Use `returnValue` to determine how to resolve `Promise` in `confirm` for `asyncDialog.js`
> Improve `<dialog>` compatibility

- math-shims.js
> Fix creating `Math.log2` method

- functions.js
Use `('serviceWorker' in navigator)`
> Fix detecting service worker support

- shims.js
This is hard-coded with the best defaults available.
Also sets `navigator.connection.type = 'unknown'` if not available.
> Add shim for `navigator.connection`

- functions.js
Because only Firefox makes `Error`s useful with data like `fileName` & `lineNumber`.
> Update `reportError` to handle `ErrorEvent`s instead

- EventTarget.js
Use a local `WeakMap` to prevent access to actual dispatcher of events in shim.
Also remove debugging code (`console.info`)
> Make event target element private

- .eslintrc.json
- CHANGELOG.md
- analytics.js
- hash.js
- package-lock.json
- package.json
- sha1.js
- shims.js
- test/index.js
- Single module as wrapper for `crypto.subtle.digest`
- Shim for [`ParentNode.replaceChildren()`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/replaceChildren)
- Update eslint config and do not use project-wide globals
- Uninstall eslint-babel plugin
> Add shim for ParentNode.replaceChild()

- CHANGELOG.md
- notification-shim.js
- shims.js
Use HTMLNotificationElement if notification permission denied or if Chrome on Android, which lies about support for Notifications.
> Add Notification shim for Android Chrome

- deprefixer.js
Note: Some old versions of Firefox use `"yes"` or `"no"` instead of `"1"` or `"0"`.
> Add `navigator.doNotTrack`

- UTM.js
For less strict requirements, only require `"utm_source"`
> Only require actually required param

- loader.js
> Properly handle async loading of `<link>`s

- CHANGELOG.md
- esQuery.js
- functions.js
- viewport.js
- Add module containing functions to wait for visibility in viewport
- Add function to check if an element is visible withing the viewport (no waiting)
- Update `$.visible()` to be more similar to jQuery's `.visible()`
- Make `$.matches()` able to test all elements or any element
> Add functionality reloating to IntersectionObserver

- viewport.js
Pass `ms` to `whenInViewportFor()` instead of `querySelector()`
> Fix passing args

- CookieStore.js
- Misc. updates to `cookieStore.delete()`
- `cookieStore.get()` returns null if no matching cookie found
> Make cookieStore more consistent with experimental API

- CHANGELOG.md
- CookieStore.js
- Update `cookieStore` to match behavior experienced in Origin-Trail in Chrome
- Fix missing params in `cookieStore.delete()` causing cookies to not be deleted
- Fix `cookieStore.delete()` only deleting single cookie
> More cookieStore fixes

- CookieStore.js
Since `document.cookie` returns an empty string when no
cookies are set, return an empty array in this case.
> Fix returning invalid cookies when no cookies set

- CHANGELOG.md
- esQuery.js
`$.on()` and `$.off()` now also accept an array of events or an object of `{ event: callback }`
```js
$('.selector').on(['click', 'dblclick'], handler, { passive: true });
$('.other').on({ contextmenu: console.log, mouseenter: myFunc);
```
> Update `$.on()` & `$.off()` to handle multiple events

- .eslintrc.json
- CHANGELOG.md
- Notification.js
- UTM.js
- dataHandlers.js
- deprecatedFunctions.js
- esQuery.js
- functions.js
- json_response.js
- mutations.js
- package-lock.json
- package.json
- polyfills.js
- popstate.js
- supports.js
- test/index.css
- test/index.js
- wysiwyg.js
- Add `ready`, `loaded`, `mediaQuery`, & `getLocation` static methods to `esQuery`
- Move deprecated function in `functions.js` to separate script
- Set `esQuery` static methods on the `$` function when exporting
- Rename `wait()` to `sleep()` and alias old function with warning
- Misc. updates to reuse functions instead of repeating them
- Update linting & dependencies
> Deprecate and update functions

- CHANGELOG.md
- http.js
- Function to get files from URLs (using `Content-Type` header)
- Functions for `fetch`ing `<link>`s (useful for preloads & manifests)
```js
import { getFile, getLink } from '/http.js';
import { save } from '/filesystem.js';
getFile('/img.jpg', { accept: 'image/jpeg' }).then(save);
getLink('link[rel="manifest"]').then(({ name, icons }) => /* ... */);
```
> New HTTP function to return a `File` from a `Request`

- functions.js
- namespaces.js
- Constants for XML namespaces (SVG & XLINK)
- Update `attr()` to take an optional `{ namespace: $xmlns } ` argument
> Basic implementation of namespaces

- CHANGELOG.md
- functions.js
Simplified `ready()` and `loaded()` to be more direct and not check for custom elements defined
> Update `loaded()` and `ready()` functions

- dom.js
- svg.js
- `create() now sets `is` attribute if given
- Add optional `styles`
- Make SVG functions use `classList` instead of `classes` for consistency
> Misc. updates to DOM helper module

- CHANGELOG.md
- KeyValueStore.js
- ShoppingCart.js
- shims.js
Also adds shim for `globalThis`
```js
import { KeyValueStore } from './KeyValueStore.js';
const store = new KeyValueStore({ name: 'db', store: 'items', version: 2 });
await store.setAll({ str: 'Hello World!', num: 42, file: new File([''], name: 'empty.txt', { type: 'text/plain' }) });
await store.keys(); // ['str', 'num', 'file']
await store.has('str', 'num'); // true
await store.get('num'); // 42
await store.reset();
await store.close();
```
> Implement `KeyValueStore`  class using `indexedDB`

- CHANGELOG.md
- dom.js
- Event feature detection (`signal`, `once`, etc.)
- Use `removeEventListener` as fallback if `signal` not supported
> Add shim for `AbortSignal` handling in `addEventListener()`

- .eslintrc.json
- Deferred.js
- dom.js
- esQuery.js
- http.js
- shims.js
- Add functions to reject `Promise`s using `signal`
- Improve usage of `AbortSignal` in event handlers & HTTP requests
- Implement `Promise`-like `Deferred` class
> Improve `AbortSignal` handling and add `Deferred` (Promise-like) class

- dom.js
- esQuery.js
There seems to be no performance benefits to this, but it does cause PageSpeed Insights scores to plummet (bug in PSI?).
> Revert DOM functions to be synchronous / not use `requestAnimationFrame()`

- slot-replacement.js
Setting `<template slot="foo">` on custom elements with `shadowRoot` can be very useful for treating slotted content as inert until the custom element and shadow have been created.
> Add module for swapping out slotted content

- dom.js
Errors were being reporting about some `handleEvent` property not being callable. This makes no sense, but seems to be related to use of `once()`.
> Fix issue with `when` and `once`

- dom.js
Pass `() => reject()` as callback instead of calling `reject()` when adding listeners.
> Fix aborting for `ready()` & `loaded()`

- shims.js
These methods have good support, and should all be handled by `<script nomodule>` for polyfill.io
> Remove shims for legacy browsers

- data-share.js
- shims.js
Since Safari is an (unfortunately) common browser that does not support `<button is="share-button">`, provide a simple alternative using `data-share-*` attributes.
Also add `navigator.canShare()` to `shims.js`
> Update handling of sharing

- chain.js
Useful until optional chaining is better supported.
`navigator?.connection?.type ?? 'unknown'`;
`unchain('connection.type', { defaultValue: 'unknown', base: navigator })`
> Add module to for optional chaining

- Lock.js
- LockManager.js
- Fix bug preventing multiple pending locks from being set
- Reject on errors in `LockManager.request()`
- Throw more errors according to spec
- Fix typo when adding listener to `signal`
> Misc. bug fixes

- LockManager.js
Locks should be skipped if `ifAvailable` is set and there is an exclusive lock set.
> Fix handling of `ifAvailable` in shared locks

- LockManager.js
Make sure the lock hasn't already been cleared when handling aborts
> Fix handling of `AbortSignal`s

- Sanitizer.js
From class documentation...
```
**
* @SEE https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer/Sanitizer
* @SEE https://wicg.github.io/sanitizer-api/
*
* @TODO: Figure out handdling of `allowCustomElements` & `allowComments`
* @TODO: Expand list of `blockAttributes`, especially all `on*`
* @TODO: Figure out how to handle `allowElements`, `alloeAttributes`, and how each
*        works with their `block*` and `drop*` counterparts.
*
* @NOTE: The spec is still under development and is likely to change.
* @NOTE: This is a very imperfect implementation and may not perform very well,
*        as it may involve a lot of querying & modifying.
*/
```
> Add Sanitizer API shim

- Sanitizer.js
- dom.js
- http.js
Add support for `Sanitizer` in `dom.js` module `html()` & `parse()`
Also removes constructor arguments for `Sanitizer()` for now until it is stabilized - use default args from `Sanitizer.getDefaultConfiguration()` instead.
Resolves #356
> Implement `Sanitizer` into modules

- yieldEvents.js
Simplify `yieldEvents()` to not work by dispatching events
> Refactor `yieldEvents()`

- LockManager.js
Check `navigator.locks.query()` instead of `navigator.locks.request()`. This has the same result but avoids setting a lock.
> Improve `navigator.locks` feature detection

- svg.js
Using `svg.setAttributeNS(null, 'viewBox', viewBox)` if `viewBox` is given
> Add `viewBox` support for `createSVG()`

- promises.js
Checking for native support (`navigator.locks`) is not ideal for heavy use, so allow skipping this check when `allowFallback` is set to false.
> Allow forcing of native support check

- abort-shims.js
- abort.js
- deprefixer.js
- dom.js
- events.js
- promises.js
- pwa.js
A wide variety of enhancements to async stuff.
- New `listen()` & `once()` functions in `events.js`
- Implement `AbortSignal.abort()`
- New exported promises for events (`load`, `beforeinstallprompt`, etc)
- More updating from `window` -> `globalThis`
> More refactoring of code

- events.js
- promises.js
Handles specific keys (e.g. `'a'`, instead of any key)
Also adds function for a promise which resolves when a specified key is pressed
> Add event handlers for keyboard events

- TrustedTypes.js
> Fix bad fallback for `'empty#html'` & `'empty#script'`

- trust.js
These should still do some checks if not supported.
> Fix handling of `isHTML()`, `isScript()`, `isScriptURL()`

- SanitizerBase.js
- purify.js
- Handle attribute in a case-insensitive manner
- Create simple (non-native) sanitizer & use to create `TrustedHTML`
> Misc. Sanitizer improvements

- SanitizerBase.js
- SanitizerConfig.js
- purify.js
- Only trust URL attributes with `https:` protocol
- `trim()` attribute values when checking URLs
- Disallow `style` attributes
- Allow `data-*` attributes
> Various enhancements to Sanitizer & purify

- HMAC.js
- TextDecoder.js
- TextEncoder.js
- hash.js
- integrity.js
- shims/textEncoder.js
- Create `TextEncoder` polyfill
- Create `TextDecoder` polyfill
- Create `HMAC` class with methods to sign & verify buffers, text, & files
- Remove `md5` code from `hash.js` and just `export { default as md5 } from './md5.js';`
- Create & use various hashing consts (e.g. `SHA_512` instead of `'SHA-512'`).
> Create text encoder/decoder polyfills & hashing/crypto enhancements

- shims/map.js
- shims/weakMap.js
- It is possible that `map.get(key)` could have a value of `undefined`, so do need to check `map.has(key)` instead.
- Handle case where `map.has(key)` but no update function given
I'm returning `map.get(key)` for cases where `map.has(key)` but no update callback is given. No instructions are given for this case, but the document gives reason why it should never return `undefined`... So it should return *something*, and the current value is the only thing that makes any sense.
-  
-
> Update `.emplace()` methods to match spec

- slack.js
Since `uuidv6()` never generated a UUID-v6 and is deprecated.
> Switch to using `crypto.randomUUID()`

- shims/navigator.js
Defaulting to `false` if not already set.
> Add shim for `navigator.pdfViewerEnabled`

- dom.js
- events.js
- utility.js
Deprecates `debounce()` from `events.js` and just passes onto new functions from `utility.js`.
> Add `debounce()` & `throttle()` functions

- abort.js
These cause issues with back/forward cache as the listeners delay their events.
> Remove `unloadSignal` & `beforeUnloadSignal`

- utility.js
Returns a function to easily get URLs relative to a given base URL. Useful for getting HTML templates & stylesheets relative to a custom elements script src.
```js
const resolveURL = getURLResolver({ base: 'https://cdn.example.com', path: '/components/' });
const tmp = await getHTML(resolveURL('./tmp.html'));
```
> Create `getURLResolver()` function

- defaults.js
- disqus.js
- dom.js
- elements.js
- events.js
- loader.js
- Add module for creating specific types of elements
- Use a standardized async `loaded()` for scripts, imgs, etc
- Add module for loading Disqus comments script
- Deprecate certain old loading funcs in `dom.js`
> Update various loaders

- krv/embed.js
Unfortunately, `sandbox="allow-same-origin"` is needed
-  
-
> Fix fullscreen in KRVMaps

- math.js
Now returns `true` immediately` for the first few prime numbers, `false` for anything divisible by 2 or 5 (except 2 & 5 themselves) and doesn't check divisibility by even numbers later on. Should make it twice as fast though still in the same time range.
> Improve `isPrime()` function

- img-utils.js
- test/index.html
Also adds some helper methods and consts.
Updates CSP to allow `data:` & `blob:` URIs for image.
> Add `resizeImageFile()` to `img-utils.js`

- dom.js
- http.js
- promises.js
- shims/function.js
- utility.js
- Update `Function.prototype.once` shim
- Update `callOnce` in `utility.js`
- Remove Promise consts for `beforeunload` & `unload` events
- Wrap all load/ready/complete/etc functions that are single event
> Update use of call-once functions

- SanitizerBase.js
- dom.js
- elements.js
- loader.js
- sanitizerUtils.js
- test/index.js
- Update polyfill for Sanitizer API
- Add `html` to `createElement()`
- Support `TrustedHTML` & `Sanitizer` in `createElement()`
- Deprecate `html()` in `dom.js` - alias to `createElement()`
- Update `loadScript()`, `loadStylesheet()` & `loadImage()` in `loader.js`
- Support `blocking` in `<script>`s & `<link>`s
> Update use of Sanitizer & TrustedTypes API

- .eslintrc.json
- TrustedTypes.js
- attrs.js
- elements.js
- trust.js
In addition to previous work on trusted attributes. Things like setting `script.src = val` via `setProp(script, 'src', val)` are now supported and more secure.
Also makes `trustedTypes` a global.
> Implement setting of trusted properties

- Sanitizer.js
- SanitizerBase.js
- SanitizerConfigW3C.js
- sanitizerUtils.js
- Extend native `Sanitizer` with `getConfiguration()` if needed
- Add and use W3C recommended config by default
> Update Sanitizer config handling

- TrustedTypes.js
- disqus.js
- dom.js
- elements.js
- harden.js
- krv/embed.js
- krv/policy.js
- Require `TrustedScriptURL` for `<iframe src>`
- "harden" full list of "injection sinks" mentioned in proposal (`eval`, `new Function()`, `setTimeout()`, etc)
- WIP implementing trust policies e.g. for KRV Embeds & Disqus script (not sure about the `<iframe>`)
> Fully (?) harden

- CHANGELOG.md
- TrustedTypes.js
- attrs.js
- dom.js
- elements.js
- harden.js
- htmlpurify.js
- http.js
- package-lock.json
- package.json
- sanitizerUtils.js
- test/funcs.js
- test/index.html
- test/index.js
- trust-policies.js
- trust.js
- youtube.js
- Add handling of `Trusted*` in addition to strings
- Avoid converting attributes to strings or URLs
- Add support for `TrustedHTML` in `elements.js` & `dom.js`
- Provide a set of trust policies
- Update `youtube.js` to use its own policy
- Add `isTrustedType` to `trusts.js`
- Do not require parent node when sanitizing nodes
- Update creation of various elements
- A whole chain of passing trusted types along instead of converting
> Relase/2.7.1 (Integrate support for `TrustedTypes`)

- http.js
Should avoid accidentally using wrong policy
-  
-
> Handle `policy.createHTML()` early

- trust-policies.js
Also adds option to create a no-op default policy for complete lockdown.
-  
-
> Fix invalid `createScript` in GA policy

- CHANGELOG.md
- TrustedTypes.js
- disqus.js
- http.js
- test/funcs.js
- test/index.html
- test/index.js
- trust-policies.js
- trust.js
- By default attempts to load CSP from `<meta http-equiv>`
- Has option to fetch page and look at CSP headers
- Fallback is still using `[data-trusted-policies]`
- Add new pre-made policies
- Add helper methods for creating polices
- Remove obsolete `fetch#html` policy from `http.js`
- Add methods to get CSP in `http.js`
- Rewrite disqus module to use current `disqus#script-url` policy
- Misc fixes
> Add option to use CSP for `TrustedTypes` polyfill

- .eslintrc.json
- TrustedTypes.js
- utility.js
Compatible with `TrustedTypes`.
Also remove dispatching of `beforecreatepolicy` events and update `globals` in ESLint config.
> Add function to register service workers

- .eslintrc.json
- Sanitizer.js
- attributes.js
- attrs.js
- dom.js
- elements.js
- geo.js
- google-analytics.js
- harden.js
- hash.js
- htmlpurify.js
- http.js
- icons.js
- img-utils.js
- loader.js
- namespaces.js
- package.json
- pwned.js
- shims/elementInternals.js
- slack.js
- svg.js
- trust-policies.js
- trust.js
- types.js
- utility.js
- youtube.js
Also adds copyright to some scripts.
**Note**:
- `internals.states.add('--foo')` uses `._state--foo` instead of `:--foo`
- `:disabled` & `:invalid` are states, thus become `._state--disabled` & `._state--invalid`
- Associating a component to a form requires calling `internals._associateForm(form, this)` such as in `connectedCallback()`
- `MutationObserver` is used and does not have an `unobserve()` method, so junk can accumulate in complex usage
- Call `internals._associateForm(null, this)` in a `disconnectedCallback()` if needed
- `formStateRestoreCallback()` cannot realistically be polyfilled
- There is no built-in behavior when disabling elements - use `formDisabledCallback()`
- `internals._polyfilled` is set to true for checking if the additional steps are necessary
- `:--foo` is an …
> Add `ElementInternals` polyfill

- math.js
- spotify.js
- trust.js
Also adds Spotify embed creating module with `spotify#script-url` trust policy.
Also removes `whenPolicyCreated()` since policy creation events have been removed.
> Fix `createPolicy`()` in trust module and `sigma()` in math module

- loader.js
No more need to `cloneNode()` when using this.
> Auto clone frag when getting templates

- keyboard.js
- shims/element.js
- Toggle `aria-hidden`
- Changes `tabindex` as needed & reverts on `el.inert = false`
- Does *not* handle elements that have `inert` preset or `el.setAttribute('inert', '')`, etc
This relies on CSS to disable pointer events, such as in:
```css
[inert] {
pointer-events: none;
}
```
Also adds keyboard mapping module.
> Add polyfill for `inert`
