- polyfills/htmlimport.js
Just a simple swap from `"` to `'`
> Use single quotes. Fixes #8

- zq.es6
> Use template strings

- appcache_listener.es6
- popstate.es6
- wysiwyg.es6
Fixes #24 
There are still plenty left, but this should handle the majority outside of `json_response.es6`
> Use fewer anonymous functions as callbacks for events

- deprefixer.es6
- fileupload.es6
- functions.es6
- index.html
- popstate.es6
- support_test.es6
- test.es6
- zq.es6
Modules only export a default if it is the only export.
Comment out `functions.es6` `ajax` function since it is no longer used.
> Make modules compatible with spec

- zq.js
> Add zq.animate method

- Cookie.js
- test/index.js
Class has methods (mostly) similar to `URLSearchParams`.
Allows setting, getting, deleting, listing, iterating, etc.
> Create Cookie class

- test/index.html
- zq.js
- Add [Symbol.iterator] method
- Simplify values generator
- Add keys and entries generators
- Minimize reliance on `this.results` for possibly extending `Set` in
the future
> Make zQ iterable

- Calendar.js
- Gravatar.js
- SchemaData.js
- SchemaNode.js
- SchemaTemplate.js
- fetch.json
- test/assets/article.html
- test/assets/footer.html
- test/assets/list.html
- test/assets/sidebar.html
- test/funcs.js
- test/index.css
- test/index.html
- test/mutations.js
- zq.js
- Add `intersect` method, creating `IntersectionObserver`s
- Most event listener methods now accept callback, and rest params to
pass on any other arguments
- SchemaData now adds missing required properties to errors
- SchemaNode now implements more `Element.prototype` methods
- SchemaTemplate can now better handle URLs for email & telephone
145cfda37d6ac6ca2f25160e03c8a97ef1cb342f
> Add intersect handling & misc other enhancements

- LICENSE
- README.md
Add GPL-V3 license and a variety of badges from htp://shields.io
> Add GPL-v3 license & various badges

- mutations.js
> Add common mutation handlers

- mutations.js
Was missing the "./" when importing, and did not use handler for `[data-show]`
> Fix invalid import & missing show handler

- fetch.json
- json_response.js
- test/index.html
- test/index.js
- zq.js
- Add/remove class now handles multiple classes
- `attr` & `data` improvements
- Add `loadHTML` method
- Use more `zQ` methods in `json_response`
- Testing improvements
> Misc updates

- Notification.js
- deprefixer.js
- shims.js
Uses a `<dialog>` if `Notification` not supported.
This provides at least basic functionality.
> Add shim for Notification

- package.json
Seems I have not updated version in `package.json` since v1.0.0
> Version bump to 2.1.1

- shims.js
> Add `Object.fromEntries`

- esQuery.js
- shims.js
Also adds misc. helper getters to esQuery
> Add Animation.finished & Animation.ready

- shims.js
Use content-type of "text/html" for all
> Fix setting content-type for imports

- deprefixer.js
- package-lock.json
- package.json
- Improve compatibility of `requestFullscreen`
- Fix `requestFullscreen` name (was incorrect case)
- Add support for `document.fullscreen`
> Fix full screen deprefixer

- asyncDialog.js
Also add classes and style to improve look
> Fix return value for `confirm`

- haveIBeenPwned.js
- package-lock.json
- package.json
- sha1.js
- Add `sha1` script/function/module
- Add function in module to check Have I Been Pwned API
> Add SHA-1 & Have I Been Pwned

- functions.js
Use `link[rel~="import"]` to find links where `rel` contains `import`
> Handle `<link rel="blah import blah">`

- README.md
- article.json
- package-lock.json
- package.json
- share-config.js
- test/funcs.js
- test/index.css
- Replace all `chriszuber.com`
- Install `http-server` as dev dependency
> Update CDN usage

- functions.js
Try this before regular `Notification` method
Should enable for Android Chrome
> Add support for notifications via service worker

- functions.js
Using `FormData` & `navigator.sendBeacon`
> Implement error reporting to API

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/nodejs.yml
- GitHub Actions for `npm test`
- Pull Request Template
- Issue Tempalets (Bug & Feature Request)
- Code of Conduct
- Contributing Guidelines
> Add GitHub Actions & various templates / policies

- test/index.html
Was causing "mixed content" on Netlify tests
> Remove fake and insecure link

- esQuery.js
- functions.js
- Media query function
- Functions to check animation & color scheme preferences (via media queries)
- Do not `$('*').animate()` if `(prefers-reduced-motion: reduce)`
> Add JS functions to check color scheme & animation preferences

- functions.js
For PWA / manifest `display` property.
> Add function to get `display-mode`

- konami.js
Just for a little fun. This uses promises that resolve when the Konami Code is entered
> Add Konami Code handler

- share-config.js
Add `sms:?body` URI for sharing via text message
> Add SMS as sharing option

- share-config.js
- webShareApi.js
Using `navigator.clipboard.writeText` if supported.
> Add ability to share via clipboard

- webShareApi.js
And other misc. enhancements to share API shim
> Add `navigator.canShare` shim

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- EventTarget.js
- HashRouter.js
- User.js
- shims.js
- Router as specified
- `EventTarget` shim so it can be extended
- User class
- Shim for `CustomEvent`
Resolves #112
> Add Router class and other misc. essential classes

- .eslintrc.json
- .github/workflows/super-linter.yml
- Update Super Linter to latest docker image
- Update eslint config file
> Update Super Linter & eslint config

- .github/workflows/nodejs.yml
- package-lock.json
> Combine open Pull Requests

- CHANGELOG.md
- functions.js
- shims.js
- Add shims for app badges (`navigator.setAppBadge()`)
- Add helper functions for working with custom elements
- Update CHANGELOG
> Add app badges & custom elements helpers

- .eslintrc.json
- CHANGELOG.md
- Calendar.js
- SchemaTemplate.js
- ShareTarget.js
- _helpers/mutations.js
- esQuery.js
- kbd_shortcuts.js
- mutations.js
- supports.js
- test/funcs.js
- test/index.html
- webShareApi.js
Update eslint config and run `npm run fix` to apply to all scripts.
> Fix indentation on `switch`es

- .editorconfig
- CHANGELOG.md
Update `.editorconfig` to specify tab style and width
> Update editor config file

- notification-shim.js
Not the best solution, but still resolves #135
> Close Notifications in test immediately

- CHANGELOG.md
- loader.js
- test/index.html
- test/index.js
Appends scripts or stylesheets to document, waiting for `"load"` events.
> Add loading script for dynamiaclly loading scripts and stylesheets

- CHANGELOG.md
- esQuery.js
- functions.js
- `debounce()` function in `functions.js`
- `$.debounce()`
- Mark several functions and methods as deprecated, for removal in v3.0.0
> Add support for `debounce()` when handling events

- CHANGELOG.md
- loader.js
- shims.js
Loads in image in the background and returns the loaded image.
If `loading: lazy` is passed, it will return the image immediately, however, since lazy loaded images to not begin loading until appended and within the viewport.
> Add `loadImage()`

- loader.js
`typeof null` is object, so update this check
> Check that srcset is a vaild object

- CHANGELOG.md
- shims.js
Async function that just returns an empty array
> Add navigator.getInstalledRelatedApps() shim

- CHANGELOG.md
- UTM.js
Creates class extending `URL`, using `searchParams` to set / get `"utm_*"` params
> Add UTM validator and generator class

- CHANGELOG.md
- shims.js
Essentially calls `this.then(callback, callback)` with cases for success and failure. Tested to be as compatible as possible.
> Add Promise.prototype.finally shim

- CHANGELOG.md
- loader.js
This used to create functions for other preloading techniques and reduce over-all size.
> Abstract preloading, etc. with `loadLink`

- loader.js
Such as ShadowRoot, for example
> Allow appending stylesheets, etc. to non-HTMLElements

- CHANGELOG.md
- viewport.js
Since just being scrolled through might not be what is desired.
```js
whenVisbleFor('#my-ad').then(adViewedCallback);
```
> Add function to resolve when element visible for given time

- CHANGELOG.md
- package-lock.json
- shims.js
Does not actually wait until idle, but does wait for an animation frame, which might reflect performance or a better time to perform an operation.
Also combines Dependabot PR to reduce build times.
> Add shim for `requestIdleCallback()`

- CHANGELOG.md
- viewport.js
Now resolves `Promise`s with data and sets easily available data when initially intersecting/not intersecting.
> Return intersection info for viewport intersection functions

- .eslintrc.json
- CHANGELOG.md
- CookieStore.js
- package-lock.json
- package.json
- shims.js
> Implement shim for Cookie Store API

- CHANGELOG.md
- CookieStore.js
- Enable setting secure flag
- Get actual existing cookie when deleting
- Normalize params
> Misc. enhancements to CookieStore

- CookieStore.js
- `deleted[]` cookies in event have no value
- Args require a name
> Fix more issues with CookieStore shim

- dialogForm.js
- test/index.html
- timeIntervals.js
Creates such forms within a `<dialog>` and returns the selected option via an async function.
Also adds helpers for working with dates by creating constants for fixed periods of consistent time (so, no months or years).
```html
<dialog>
<form method="dialog">
<button type="submit" value="..." class="btn btn-default">...</button>
<button type="reset" class="btn btn-reject">Cancel</button>
</form>
</dialog>
```
> Implement helper to create `<form method="dialog">`s

- CHANGELOG.md
- functions.js
- shims.js
- `Add changeTagName` function
- `Add Element.prototype.getAttributeNames` shim
> Misc. enhancements

- fetch.json
- functions.js
Since this involves a custom element and a click handler, it does not require a user-initiated event to work.
> Add functions for getting & requesting Notification permissions

- CHANGELOG.md
- esQuery.js
- functions.js
- package-lock.json
- package.json
- test/assets/article.html
- test/assets/footer.html
- test/index.css
- test/index.js
- New functions: `css()`, `attr()`, `data()`, and `toggleClass()`
- Update `esQuery` methods to use new functions
- Add missing optional arguments to `$.debounce()`, allowing passive listeners
- Version bump
> Add new helper functions

- CHANGELOG.md
- data-handlers.js
- esQuery.js
- test/index.css
- test/index.html
- test/index.js
Create script with event(click) handlers using `data-*` attributes.
Also use Adwaita theme and add buttons
> Add data-handlers.js

- CHANGELOG.md
- filesystem.js
- test/index.css
- test/index.js
Module exports `open()` and `save()` functions.
This is roughly equivalent to [`FileSystemHandle` API](https://wicg.github.io/file-system-access/#api-filesystemhandle)
> Add `filesystem.js`

- CHANGELOG.md
- deprefixer.js
- esQuery.js
- uuid.js
Also deprefixes `window.msCrypto` and updates `esQuery.value()`
> Add script with functions for generating UUIDs

- CHANGELOG.md
- CookieStore.js
- data-handlers.js
- test/index.css
- test/index.html
- test/index.js
- `cookieStore.onchange`
- `hide`, `unhide`, `enable`, `disable`, and `cookie` event handlers for `data-*` attributes
- An `init()` function for `data-*` module
> Add more data-* handlers

- data-handlers.js
Use `./functions.js` for relative path instead of `/functions.js` for absolute path.
> Fix bad import

- data-handlers.js
Use `[data-scroll-to]` instead of `[data-scrollTo]`.
> Fix typo in setting handler

- CHANGELOG.md
- data-handlers.js
- test/index.js
- Add `data-*` handlers for `full-screen`, `copy`, and `navigate`
-
> More data-* handlers

- CHANGELOG.md
- functions.js
Create functions for creating `<svg>` and `<use>`
> Create SVG functions

- loader.js
- Images can now have `slot` and `part` set
- Fix early checking of `img.complete` to actually wait for load
- Fix awaiting loading of no-loading content (`<script nomodule>` and `<link disabled>`)
> Various enhancements for loaders

- CHANGELOG.md
- asyncDialog.js
- share-targets.js
- share.js
- New handling for sharing based on the [Share Target API](https://web.dev/web-share-target/)
- Swap order of ok and cancel buttons in `confirm()` in `asyncDialog.js`
> Add handling for Share Target API

- share.js
- test/funcs.js
- test/index.html
Checks for & polyfills `navigator.share()` and `navigator.canShare()`.
Also add `<button is="share-button">` for testing.
> Add share polyfill function

- CHANGELOG.md
- functions.js
> Add various new async event handling functions

- CHANGELOG.md
- esQuery.js
- functions.js
- haveIBeenPwned.js
- http.js
- package-lock.json
- package.json
Add HTTP library with `GET`, `POST`, `DELETE`, and other methods
> Add HTTP library

- esQuery.js
- functions.js
- http.js
- Allow parsing HTML as document or document fragment
- Add `getText()` and `postText()`
> Enhance HTTP methods

- CHANGELOG.md
- functions.js
Similar to `window.open()`, but builds the windowFeature string using `{ height: 400, width: 800, opener: true }` with default values set.
> Add `openWindow()` function

- .github/workflows/nodejs.yml
- esQuery.js
- package-lock.json
- timeIntervals.js
Check if `esQuery()` constructor argument is an `Element` to avoid using `selector[Symbol.iterator]`
> Fix handling $(document.forms[name])

- CHANGELOG.md
- meta.js
- test/index.html
- test/index.js
Create module for adding and updating `<meta>`s such as keywords, description, etc.
Also provides functions for getting page metadata.
> Add module for working with `<meta>`s

- CHANGELOG.md
- functions.js
Async helper function `statusDialog()` for creating `<dialog>`s
> Create `statusDialog()` function

- CHANGELOG.md
- date-consts.js
- timeIntervals.js
`date-consts.js` module exporting 0-indexed array of days and months. Also exports `SECONDS` - `YEARS`.
> Add new Date constants module

- CHANGELOG.md
- google-analytics.js
Now has multiple helper and wrapper methods
> Update Google Analytics script

- shims.js
Set to match errors thrown when not it or n is negative.
> Make `navigator.setAppBadge()` work via title

- dom.js
- esQuery.js
- shims.js
- Add new `query()` function to dom module
- Refactor dom module to use this function for `css()`, `attr()`, etc.
- Add new `observe()` function to dom module
- Use `query()` when constructing `esQuery()` class
- Add shim for `queueMicrotask()`
> Misc. enhancements to dom.js and related modules

- dom.js
- esQuery.js
- Fix spelling in `intersect` function
- Use `intersect()` in `esQuery` class method
- Add new `animate()` function
> Fix typo & misc. enhancements

- dom.js
- esQuery.js
- Handle objects & arrays differently in `toggleClass()`
- Add new Promise-based `onAnimationFrame()` & `onIdle()`
- Make most DOM impacting functions and methods work using `onAnimationFrame()`
- Also updates methods in esQuery
> Fix invalid logic in `toggleClass()`

- CHANGELOG.md
- ShoppingCart.js
Uses IndexedDB for storing and modifying basic shopping cart data. Capable of producing `total` & `displayItems` for a `PaymentRequest`
> Implement IndexedDB based ShoppingCart class

- CHANGELOG.md
- EventObserver.js
- ShoppingCart.js
- dom.js
- esQuery.js
Add `EventObserver` class, which is a generator `yield`ing dispatched events
- Misc. `dom.js` enhancements
- New `ShoppingCart.cursor()` async generator
> Add `EventObserver` class

- http.js
Creates and submits a form using given data and `target` & `enctype`.
> Add postNav function

- .gitattributes
- IDB.js
Also fix misc. issues with IDB.
> Force usage of LF as text file EOL

- Deferred.js
Now resolves/rejects based on given events. Also has async generator method `async *yieldEvents()`
> Enhancements to `Deferrered`

- Deferred.js
- abort.js
- asyncDialog.js
- dom.js
- functions.js
- loader.js
- promises.js
- protectedData.js
- pwa.js
- Make better use of existing modules
- Implement & use simple deferreds
> Misc module updates

- promises.js
`yield`s the results of promises in the order they are resolved.
> Add promiseQueue async generator

- abort.js
- functions.js
- geo.js
- promises.js
- Move `sleep()` to `promises.js` with support for `signal`
- Methods for abortable timeouts & intervals
- New geo module
- async generators for events and callbacks
> Misc. enhancements to promise/abort modules

- dom.js
- esQuery.js
- events.js
- media-queries.js
- Implement for `animate()`, `intersect()`, & `mutate()` in `dom.js`
- Extend those to `esQuery.js` methods
- Update media queries module
> Add more `AbortSignal` support

- abort.js
- yieldEvents.js
Also adds a simple `isAborted(signal)` function.
> Add `yieldEvents` via module

- dom.js
Mostly querying using the wrong var.
> Fix misc DOM mopdule errors

- abort.js
- dom.js
- events.js
- promises.js
- Move some functions to different modules (where they belong)
- Add new abortable methods for `requestAnimationFrame` & `requestIdleCallback`
> Misc. cleanup & enhancements

- abort.js
- dom.js
- pwned.js
Need to map `signal`s to `Promise`s.
Also adds:
- New function to create an `AbortController` that aborts on `<button>` click
- `once()` function in DOM module
- Event handler function for pwned module using `setCustomValidity()` on inputs
> Fix bad promise logic

- assert.js
Not useful in Node since Node doesn't do modules correctly, but it's useful for tests in browser Can work with DOM elements, async functions and Promises.
> Create assert module

- Notification.js
- functions.js
- math.js
- popup.js
- share.js
- Import `css` from DOM module instead of functions
- Add new popup module
- Move `between()` to math module
> More misc. cleanup

- shims.js
Also adds `AggregateError` class extending `Error`
> Add shims for `Promise.race()` and `Promise.any()`

- shims.js
See [`reportError()`](https://developer.mozilla.org/en-US/docs/Web/API/reportError)
> Add new `reportError()` function

- shims.js
> Add shim for `crypto.randomUUID()`

- speech.js
Namely, Chrome on Android doesn't seem to support `SpeechSynthesisVoice` for some reason.
> Handle browsers that don't support voices

- pwa-install.js
Forgot `event.preventDefault()`
> Prevent showing native install banner

- uuid.js
> Update `uuidv6()` to use `crypto.getRandomValues()`

- Lock.js
- LockManager.js
Note: This is based off of the draft spec and does not work across browsing contexts (maybe implement something with service worker?)
> Implement shim for WebLocks API

- AsyncLock.js
- LockManager.js
- abort-shims.js
- promises.js
Also misc. enhancements to various async operations
> Add wrapper class for `navigator.locks`

- AsyncLock.js
- CookieStore.js
- LockManager.js
- dom.js
- math.js
- promises.js
- shims.js
- uuid.js
Just a little rafactoring & cleanup.
Change `AsyncLock`, which was recently added. It now takes `name` only in contructor
> Misc. enhancements & updates

- Sanitizer.js
Just trying to make this more consistent with experimental implementation in Firefox.
> Compatibility updates

- LockManager.js
- promises.js
- Add new `lock()`
- Add `onTimeout()`
- Update `onAnimationFrame()`, `onIdle()`, & `sleep()`
- Misc. refactoring & cleanup
> Misc. async enhancements

- AsyncTaskQueue.js
Good for queuing up a series of tasks to be executed asynchronously. More tasks may be scheduled using the `.add(callback)` method.
> Create `AsyncTaskQueue` class

- AsyncTaskQueue.js
> Fix passing callbacks in `AsyncTaskQueue` constructor

- CookieStore.js
- SanitizerBase.js
- dom.js
- http.js
- sanitizerUtils.js
- shims.js
- shims/all.js
- shims/cookieStore.js
- shims/locks.js
- shims/sanitizer.js
- shims/trustedTypes.js
- test/index.html
- test/index.js
- theme-cookie.js
Most important changes:
- New scripts to import to immediately polyfill locks, trustedTypes, cookieStore, & sanitizer
- New trust policy for HTTP module for when fetching HTML given `integrity`
> Misc. enhancements & better implement TrustedTypePolicies

- integrity.js
This will be very useful in development...
> Add new `fromFile()` to `integrity.js`

- shims/trustedTypes.js
> Remove debugging info

- SanitizerBase.js
> Handle `JAVASCRIPT:` URLs in a case-insensitive manner

- purify.js
> Do not allow `<noscript>` tags

- SanitizerConfigBase.js
> Update list of blocked/dropped tags

- SanitizerConfigBase.js
- purify.js
Look at me, I'm dropping the `<base>`!
> Disallow `<base>`

- SanitizerBase.js
- purify.js
- shims.js
- `purify` now performs check correctly
- Automatically allow `location.protocol` for `http:` origins,etc.
> Fix checking URL attrs by protocol

- http.js
Simplifies setting UTM params using `setURLParams()`
-  
-
> Add `setUTMParams()`

- geo.js
> Fix bad handling of `signal`

- dom.js
- math.js
- shims.js
- shims/array.js
- shims/set.js
- Add shims for [Stage 2 Set methods](https://github.com/tc39/proposal-set-methods)
- Implement `groupBy()` & `groupByToMap()` in DOM module
> Implement shims for `Set` operations

- math.js
Creates simple `divisibleBy`, `even`, & `odd` functions.
Deprecates old `clamp` function, which is `Math.clamp` with different order for args.
> Add misc. functions

- shims/array.js
- shims/map.js
- shims/weakMap.js
> Update `arr.groupByToMap()` to use `map.emplace()`

- dom.js
- intersect.js
Returns a `Promise` which resolves when an element `isIntersecting`.
> Add async fn for handling `IntersectionObserver`

- shims.js
- shims/window.js
See https://web.dev/multi-screen-window-placement/
> Implement `window.getScreenDetails()`

- shims/abort.js
> Add `AbortSignal.timeout` shim

- dom.js
Adds `whenPageVisibile()` and `whenPageHiden()`
> Add async functions for page visibility

- math.js
Instead of using `Math.clamp()`
> Revert to using `clamp()`

- math.js
- utility.js
Also updates `randomInt()` to use `crypto`
> Add `random()` & `rng()` functions

- geo.js
> Misc. cleanup

- frame-rate.js
- shims/performance.js
Also adds shim for `requestAnimationFrame()`.
Misc. updates to calculating frame rates.
> Update `requestIdleCallback()` shim

- DataURI.js
- math.js
> Misc. Math enhancements & `DataURI` class

- SanitizerBase.js
- dom.js
- sanitizerUtils.js
Also refactors Sanitizer API polyfill
Resolves #452
> Add support for `options` object in `create()` from `dom.js`

- shims/element.js
> Fix `sanitizer` param in `Element.prototype.setHTML`

- dom.js
- `interactive()` for the interactive state
- `complete()` for the complete state
- `whenReadyState()` for arbitrary states
- `readyStateIndex()` for states as integers
> Implement ready state promises

- dom.js
> Improve `signal` support in `ready()` & `loaded()`

- HTTPException.js
- http.js
Pretty much combines `Error` with `Response`. Useful to throw when `! resp.ok`.
```js
fetch(url).then(resp => throw new HTTPException(resp, { cause: new DOMException('Request failed') }))
```
> Implement `HTTException` class

- HTTPException.js
- http.js
> Improve HTTPException

- math.js
- passwordGenerator.js
- Update `sum()` function
- Add `product()` function
- Implement basic password generator built on `crypto`
> More misc. stuff

- abort.js
- shims/abort.js
Also custom implementation  (`anyAbortedSignal()`) to use in case the spec is abandoned/changed.
> Add shim for `AbortSignal.any()`

- math.js
- promises.js
- shims.js
- shims/array.js
- shims/function.js
- shims/iterator.js
- shims/number.js
- shims/promise.js
- utility.js
- `Function.prototype.once()`
- `Promise.try()`
- `Number.range()`
- `Iterator.prototype.take()` etc
##Changed
- Renamed to `Array.prototype.group()`
-  
-
> Add multiple upcoming JS shims

- shims/array.js
- utility.js
Also add functions such as `isNull()`.
> Add more new experimental array methods

- TrustedTypes.js
> Allow duplicate policies by default

- TrustedTypes.js
> Use static getting to check `TrustedTypeFactory.allowDuplicates`

- krv/apps.js
- krv/events.js
- krv/places.js
- krv/wfd.js
> Add helper modules for KRV

- elements.js
> Add `createIframe()`

- elements.js
Allows setting complex feature policies.
> Allow more complex `allow` in `createIframe()`

- elements.js
> Add `part`, `title`, & `slot` to `<iframe>`s

- krv/embed.js
> Add module for embedding KRV iframes

- krv/embed.js
> Support selecting marker by id (target)

- krv/places.js
> Add missing `getBusinesses()`

- elements.js
- utility.js
- Add `isObject()` for reliable checking if thing is an object
- Switch from `data` to `dataset` when creating elements
> Misc. fixes/enhancments

- disqus.js
Use `dataset: { timestmap }` instead of `data: { timestamp }`.
> Set `data-timestamp` correctly

- krv/embed.js
> Allow adding images in WFD Events

- elements.js
- youtube.js
Also adds `allowFullscreen` if in `allow`
> Add module for embedding YouTube videos

- krv/embed.js
> Add `styles` & `data` & `slot` & `part` as optional args

- krv/embed.js
- svg.js
Adds support for new attributes and provides functions for creating all standard shapes.
Also updates KRV Embed module for upcoming work on KRV Maps and setting `fetchPriority`, etc.
> Enhance SVG module

- elements.js
> Fix setting `<iframe allow="...">`

- shims/map.js
Update to new value... was re-setting to old value.
-  
-
> Fix updating in `emplace()`

- disqus.js
> Fix importing of `createScript`

- attrs.js
> Create module for typed attrs

- attrs.js
> Add `fallback`, `maxLength`, & `pattern` options

- elements.js
- states.js
- test/index.html
- utility.js
- Add functions to create `<input>`, `<select>`, & `<datalist>` etc
- Add list of states/territories
- Make `isNullish()` return `false` for `NaN`
- Add `<meta name="color-scheme">` to test index page
This allows for the following:
```js
import { STATES } from './states.js';
import { createSelect } from './elements.js';
export function createStateSelect(name = 'state') {
const { states, armedForces, territories } = STATES
.map(({ abbr: value, name: label, group }) => ({ label, value, group }))
.group(state => state.group);
return createSelect(name, [
{ label: 'Select a State/Region', value: '', disabled: true },
...states,
{ label: 'Armed Forces', options: armedForces },
{ label: 'Territories', options: territories },
], {
id: 'state',
classList: ['input'],
autocomplete: 'address-level1', …
```
> Add helper functions for forms

- elements.js
> Add support for `inputMode`

- shims/array.js
> Add shims for Change Array by copy proposal

- math.js
> Add decent `isPrime()` function

- img-utils.js
Useful for working between `<img>`, `File`, & `<canvas>`
> Create image utility module

- error-handler.js
> Add basic error handler module

- img-utils.js
> Misc changes to creating images, etc

- attrs.js
- elements.js
Also introduces `getAttrs()` in `attrs.js`.
> Create `copyAs(`) in `elements.js`

- http.js
> Add `navigateTo()` function to `http.js`

- .eslintrc.json
- img-utils.js
- Add `previewImgOnChange()` to generate previews
- Add `resizeImageFiles()`, handling an array if files
- Update `resizeImageFile()` to use `scheduler.postTask()`
> Add function to generate `<input type="file">` img previews

- icons.js
- svg.js
Also updates `svg.js` to support `dataset`, `events`, and better handle other attributes in `rest`.
> Add spinner icon

- attrs.js
> Add min/max in getting ints & floats

- dom.js
- http.js
- icons.js
- img-utils.js
- loader.js
- svg.js
- types.js
> Even more icons in `icons.js`

- http.js
> Fix importing types module

- utility.js
> Fix setting UTM params

- shims/iterator.js
- shims/number.js
> Add `Iterator.range` polyfill

- .eslintrc.json
- math.js
- shims/number.js
> Warn about & replace use of `Number.range()`

- utility.js
> Add new type-detection functions

- promises.js
> Remove most const page event promises

- promises.js
> Disable more event/promises

- .eslintrc.json
- tests.js
- utility.js
> Add basic testing module

- img-utils.js
- Deal with SVGs with no `width` or `height`
- Add methods to get image dimensions & info
> Improve handling if image sizing

- TrustedTypes.js
- attrs.js
- dom.js
- elements.js
- test/index.js
- trust.js
- Support setting attributes as TrustedTypes as needed
- Improve polyfills
> More widely implement `TrustedTypes`

- harden.js
> Do not overwrite methods if trustedTypes native

- Sanitizer.js
- SanitizerBase.js
- package.json
- sanitizerUtils.js
> Fix passing Sanitizer config

- elements.js
> Fix setting `src` as a `TrustedScriptURL`

- TrustedTypes.js
> Remove debugging logging

- shims/element.js
> Add polyfill for `<template shadowrootmode="...">`

- shims.js
- shims/elementInternals.js
- shims/symbols.js
> Add `ElementInternals.states` shim

- shims/element.js
- shims/elementInternals.js
> Fix issue with `ElementInternals` & `<template>`

- trust.js
> Fix check in `isTrustedType()`

- http.js
- loader.js
- test/index.html
Also updates `http.js` module to support `priority` & fixes trusted types allowed.
> Create template getter - helper function

- attrs.js
> Fix stringifying CSS values

- Color.js
- attrs.js
- color-utils.js
- math.js
- utility.js
> Add & use `color-utils` module

- elements.js
> Add function just to create `<slot>`s

- math.js
- All RNG generators are all now infinite
- Support unsigned 8/16/32 bit int RNG generators
> Improve RNG support

- utility.js
> Fix registering SW with Trusted Script URLs

- icons.js
> SVG icons have `role="presentation"`
